services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8001:8000"  # External port 8001 maps to internal port 8000
    depends_on:
      db:
        condition: service_healthy  # Ensures DB is ready before Django starts
    env_file:
      - .env  # ✅ Loads your .env file into the container

    volumes:
      - .:/code  # Mounts your code into the container
    networks:
      - art_moving_network

  db:
    image: postgres:15  # Latest stable version
    container_name: matthew_raynor_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
    networks:
      - art_moving_network

volumes:
  postgres_data:

networks:
  art_moving_network:
